version: 1.0.{build}
configuration: Release
platform: x86
clone_folder: C:\tympan\src
environment:
  VisualStudioVersion: 10.0
install:
- ps: >-
    Add-Type -AssemblyName System.IO.Compression.FileSystem

    $cachedir='C:\tympan\cache\'

    $srcdir='C:\tympan\src\'

    if (-Not (Test-Path $cachedir)) {
      mkdir $cachedir
    }

    $thirdparties='Code_TYMPAN-4.7_third-party-05.zip'

    $zipfile=$cachedir + $thirdparties

    if (-Not (Test-Path $zipfile)) {
      (new-object net.webclient).DownloadFile('https://bitbucket.org/TYMPAN/code_tympan/downloads/' + $thirdparties, $zipfile)
    }

    [System.IO.Compression.ZipFile]::ExtractToDirectory($zipfile, $srcdir + '3rdparty')
cache:
- C:\tympan\cache -> appveyor.yml
- C:\Miniconda\pkgs -> appveyor.yml
build_script:
- cmd: >-
    cd C:\tympan\
          
    md build

    cd build

    set MINICONDA=C:\Miniconda34
    
    set PYTHONPATH=%MINICONDA% 

    set PATH=%MINICONDA%;%MINICONDA%\Scripts;%MINICONDA%\Library\bin;%MINICONDA%\libs;%MINICONDA%\DLLs;%MINICONDA%\Library\lib

    set PATH=%PATH%;C:\Windows\system32;C:\Windows;C:\tympan\build;C:\Program Files (x86)\CMake\bin

    echo %PATH%

    set TYMPAN_PYTHON_INTERP=%MINICONDA%\python.exe
    

    conda install -y -q cmake=3.6.3
    
    conda install -y -q boost=1.51.0 -c logilab
    
    conda install -y -q cython=0.26
    
    conda install -y -q numpy=1.10.1
    
    conda install -y -q scipy=0.16.0 
    
    conda install -y -q matplotlib=1.5.1
    
    conda install -y -q pandas=0.18.1
    
    conda install -y -q xlsxwriter=0.9.6

    conda install -y -q geos=3.4.2

    conda install -y -c scitools/label/archive shapely

    conda install -y -q swig=3.0.10

    conda install -y -q gmp=5.0.1 mpfr=3.0.0 -c salilab

    conda install -y -q cgal=4.3 -c logilab
    
    conda install -y -q sphinx=1.2.2=py34_2 graphviz 
    
    conda install -y -q doxygen -c omnia

    conda install -y -q qt=4.8.7=vc10_9
    
    conda list


    cmake -G"Visual Studio 10" -DCMAKE_BUILD_TYPE=Release -DPYTHON_LIBRARY=%MINICONDA%\libs\Python34.lib ..\src

    cmake --build . --config Release
    
    call SetEnvTympanTests.bat
    
    echo 'TOTOLERIGOLO'
    
    echo %PATH%
    
    echo %PYTHONPATH%
    
    echo 'dirdir'
    
    dir
    
    ctest -C Release --output-on-failure
    
