version: 1.0.{build}
configuration: Debug
clone_folder: c:\tympan\src
platform: x86
environment:
  VisualStudioVersion: 10.0
install:
- ps: >-
    Add-Type -AssemblyName System.IO.Compression.FileSystem


    $cachedir='c:\tympan\cache\'

    $srcdir='c:\tympan\src\'

    if (-Not (Test-Path $cachedir)) {
      mkdir $cachedir
    }

    $thirdparties="Code_TYMPAN-4.7_third-party-05.zip"

    $zipfile=$cachedir + $thirdparties

    if (-Not (Test-Path $zipfile)) {
        (new-object net.webclient).DownloadFile('https://bitbucket.org/TYMPAN/code_tympan/downloads/' + $thirdparties, $zipfile)
    }


    [System.IO.Compression.ZipFile]::ExtractToDirectory($zipfile, $srcdir + '3rdparty')
cache:
- c:\tympan\cache
- C:\Miniconda\pkgs
build_script:
- cmd: >-
    cd c:\tympan\

    md build

    cd build


    echo %PATH%

    set PATH=C:\Miniconda3;C:\Miniconda3\Scripts;C:\Miniconda3\Library\bin;C:\Miniconda3\libs

    set PATH=C:\Program Files (x86)\MSBuild\12.0\Bin;%PATH%

    set PATH=%PATH%;C:\Windows\system32;C:\Windows;C:\Program Files (x86)\CMake\bin;

    echo %PATH%

    conda install -y -q cython numpy

    conda install -y -q qt=4.8.7=vc9_5 boost cgal swig -c defaults -c salilab

    conda list


    cmake -G"Visual Studio 10" -DCMAKE_PREFIX_PATH=C:\Miniconda\envs\tympan ..\src


    cmake --build . --config Debug
test_script:
- cmd: >-
    cd build

    ctest --output-on-failure
